library(brainflow)

args = commandArgs (trailingOnly = TRUE)
board_shim <- get_board_shim_object(as.integer(args[1]), args[2])
board_shim$prepare_session()
board_shim$start_stream()
Sys.sleep(time = 5)
board_shim$stop_stream()
data <- board_shim$get_current_board_data(as.integer(250))
board_shim$release_session()
